apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-api
  name: sample-api-svc
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sample-api
